**Created On:** July 16, 2025\
**Author:** Hao Liu

- This notebook is to test new data received on 20250716

In [4]:
import sys
import os
import pandas as pd

# Add the `src` folder to the system path
sys.path.append(os.path.abspath('../src'))

# Now you can import
from fluorescence_fit import preprocess_data_auto, analyze_fluorescence_decay_triton, analyze_fluorescence_decay_no_triton,\
analyze_fluorescence_decay_no_triton_numerical

In [10]:
file_path = '../../data/data_20250716/20250716_DOPC.xlsx'
sheet_name = "Fluorescence 1_03"
df_clean, filename = preprocess_data_auto(file_path, sheet_name)

In [11]:
df_clean

,avg. time [s],0.64 DOPC in HEPES (A02),0.64 DOPC in HEPES (A03),0.64 DOPC in HEPES (A04),0.64 mm DOPC in HEPES + Triton (A06),0.64 mm DOPC in HEPES + Triton (A07),0.64 mm DOPC in HEPES + Triton (A08)
0,0.00,73.3758,104.0560,130.4520,15.595600,23.336200,18.919200
1,3.85,68.1666,99.9866,127.0560,6.539150,10.145200,8.821320
2,7.69,64.1851,97.6961,117.4010,3.990100,5.780820,5.395790
3,11.49,62.5501,95.5163,115.8250,2.587510,3.510080,3.352350
4,15.14,63.1694,95.3215,114.2520,1.632070,2.165360,2.190020
...,...,...,...,...,...,...,...
596,1889.12,41.5770,58.6896,69.2230,0.463639,0.446689,0.459505
597,1892.04,37.8784,60.4496,67.5681,0.480134,0.465325,0.466125
598,1894.74,36.7396,62.2763,68.5231,0.493276,0.443773,0.431406
599,1897.73,37.8549,63.1264,72.7031,0.458975,0.455945,0.466245
600,1900.93,38.0539,65.1321,72.0572,0.476369,0.471384,0.459101

In [12]:
# Need self choose the time_range for fitting
results11 = analyze_fluorescence_decay_triton(df_clean, filename, time_range=10)
results11

Trial 1: R^2 = 0.9138, RMSE = 0.2795
Trial 2: R^2 = 0.9379, RMSE = 0.2671
Trial 3: R^2 = 0.9463, RMSE = 0.2325
Saved: 20250716_DOPC_fit_params_Triton.csv
Saved: 20250716_DOPC_fit_plot_Triton.png
Saved: 20250716_DOPC_residual_plot_Triton.png

                F0     k_deg  R_squared      RMSE
Trial 1   9.139666  0.092075   0.913845  0.279550
Trial 2  14.381837  0.104962   0.937899  0.267065
Trial 3  12.450733  0.098661   0.946255  0.232500

In [13]:
results22 = analyze_fluorescence_decay_no_triton(df_clean, filename, p0 =[25, 25, 0.01, 0.001, 0.005])
results22

Saved fit plot to: 20250716_DOPC_fit_plot_noTriton.png
Saved residual plot to: 20250716_DOPC_residual_plot_noTriton.png
Saved parameters to: 20250716_DOPC_fit_params_noTriton.csv

,Trial,F_out0,F_in0,k_deg_out,k_deg_in,k_perm,R_squared,RMSE
0,0.64 DOPC in HEPES (A02),13.551163,51.148705,0.007277,0.000162,0.007124,0.908177,1.767810
1,0.64 DOPC in HEPES (A03),19.085115,78.826152,0.013517,0.000146,10.000000,0.920886,2.087018
2,0.64 DOPC in HEPES (A04),26.352658,90.120914,0.009268,0.000141,10.000000,0.924920,2.603749

In [14]:
results23 = analyze_fluorescence_decay_no_triton_numerical(df_clean, filename)
results23

Results saved to ../../results/20250716_DOPC_20250716-17:10

,Trial,F_out0,F_in0,k_deg_out,k_deg_in,k_perm,R_squared,RMSE
0,Trial_1,13.561023,49.998175,0.007288,0.000162,0.007130,0.908210,1.767487
1,Trial_2,19.923468,77.960810,0.013476,0.000146,0.013337,0.920908,2.086724
2,Trial_3,27.746503,88.749112,0.009280,0.000141,0.009154,0.924948,2.603264